# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/form/array_field.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(952, 825)
        Form.setStyleSheet("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lfbArrayGroup = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lfbArrayGroup.setFont(font)
        self.lfbArrayGroup.setStyleSheet("QGroupBox#lfbArrayGroup{\n"
"    background: rgba(0,0,0,0.05);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.lfbArrayGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.lfbArrayGroup.setObjectName("lfbArrayGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.lfbArrayGroup)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lfbArrayFormGroup = gui.QgsCollapsibleGroupBox(self.lfbArrayGroup)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lfbArrayFormGroup.setFont(font)
        self.lfbArrayFormGroup.setStyleSheet("QgsCollapsibleGroupBoxBasic{\n"
"    background: rgba(0,0,0,0.1);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QgsCollapsibleGroupBoxBasic { border: none; }\n"
"\n"
"QgsCollapsibleGroupBoxBasic::title, QgsCollapsibleGroupBox::title {}")
        self.lfbArrayFormGroup.setCollapsed(True)
        self.lfbArrayFormGroup.setObjectName("lfbArrayFormGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.lfbArrayFormGroup)
        self.gridLayout_3.setContentsMargins(10, 0, 1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lfbArrayInput = QtWidgets.QGridLayout()
        self.lfbArrayInput.setContentsMargins(-1, 25, -1, -1)
        self.lfbArrayInput.setObjectName("lfbArrayInput")
        self.gridLayout_3.addLayout(self.lfbArrayInput, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.lfbAddBtn = QtWidgets.QPushButton(self.lfbArrayFormGroup)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lfbAddBtn.setFont(font)
        self.lfbAddBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbAddBtn.setStyleSheet("QPushButton{\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"    padding:10px;\n"
"    margin: 10px;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:transparent;\n"
"    color: rgba(0,0,0,0.3);\n"
"}")
        self.lfbAddBtn.setObjectName("lfbAddBtn")
        self.horizontalLayout_5.addWidget(self.lfbAddBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.lfbArrayFormGroup)
        self.lfbArrayOutput = QtWidgets.QTableWidget(self.lfbArrayGroup)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lfbArrayOutput.setFont(font)
        self.lfbArrayOutput.setStyleSheet("")
        self.lfbArrayOutput.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lfbArrayOutput.setAlternatingRowColors(True)
        self.lfbArrayOutput.setTextElideMode(QtCore.Qt.ElideNone)
        self.lfbArrayOutput.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lfbArrayOutput.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lfbArrayOutput.setObjectName("lfbArrayOutput")
        self.lfbArrayOutput.setColumnCount(0)
        self.lfbArrayOutput.setRowCount(0)
        self.lfbArrayOutput.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.lfbArrayOutput)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.lfbArrayGroup)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbArrayGroup.setTitle(_translate("Form", "GroupBox"))
        self.lfbArrayFormGroup.setTitle(_translate("Form", "Hinzufügen"))
        self.lfbAddBtn.setText(_translate("Form", "Hinzufügen"))
        self.lfbArrayOutput.setSortingEnabled(False)
from qgis import gui
