# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/form/boolean.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(865, 485)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 20, 0, 20)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lfbTextFieldDescriptionBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbTextFieldDescriptionBtn.sizePolicy().hasHeightForWidth())
        self.lfbTextFieldDescriptionBtn.setSizePolicy(sizePolicy)
        self.lfbTextFieldDescriptionBtn.setStyleSheet("QPushButton{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin-right: 10px;\n"
"}")
        self.lfbTextFieldDescriptionBtn.setObjectName("lfbTextFieldDescriptionBtn")
        self.horizontalLayout.addWidget(self.lfbTextFieldDescriptionBtn)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lfbTextFieldLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbTextFieldLabel.sizePolicy().hasHeightForWidth())
        self.lfbTextFieldLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lfbTextFieldLabel.setFont(font)
        self.lfbTextFieldLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lfbTextFieldLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lfbTextFieldLabel.setObjectName("lfbTextFieldLabel")
        self.verticalLayout.addWidget(self.lfbTextFieldLabel)
        self.lfbTextFieldHelp = QtWidgets.QLabel(Form)
        self.lfbTextFieldHelp.setObjectName("lfbTextFieldHelp")
        self.verticalLayout.addWidget(self.lfbTextFieldHelp)
        self.lfbTextFieldError = QtWidgets.QLabel(Form)
        self.lfbTextFieldError.setStyleSheet("color: red;")
        self.lfbTextFieldError.setObjectName("lfbTextFieldError")
        self.verticalLayout.addWidget(self.lfbTextFieldError)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lfbCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbCheckBox.sizePolicy().hasHeightForWidth())
        self.lfbCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lfbCheckBox.setFont(font)
        self.lfbCheckBox.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.lfbCheckBox.setText("")
        self.lfbCheckBox.setIconSize(QtCore.QSize(25, 25))
        self.lfbCheckBox.setObjectName("lfbCheckBox")
        self.horizontalLayout.addWidget(self.lfbCheckBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbTextFieldDescriptionBtn.setText(_translate("Form", "i"))
        self.lfbTextFieldLabel.setText(_translate("Form", "TextLabel"))
        self.lfbTextFieldHelp.setText(_translate("Form", "Help"))
        self.lfbTextFieldError.setText(_translate("Form", "ErrorLabel"))
