# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/form/dropdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(819, 354)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 20, 0, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.lfbTextFieldError = QtWidgets.QLabel(Form)
        self.lfbTextFieldError.setStyleSheet("color: red;")
        self.lfbTextFieldError.setObjectName("lfbTextFieldError")
        self.gridLayout.addWidget(self.lfbTextFieldError, 5, 1, 1, 1)
        self.lfbTextFieldSuccess = QtWidgets.QLabel(Form)
        self.lfbTextFieldSuccess.setStyleSheet("color: green;")
        self.lfbTextFieldSuccess.setObjectName("lfbTextFieldSuccess")
        self.gridLayout.addWidget(self.lfbTextFieldSuccess, 6, 1, 1, 1)
        self.lfbTextFieldLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbTextFieldLabel.sizePolicy().hasHeightForWidth())
        self.lfbTextFieldLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lfbTextFieldLabel.setFont(font)
        self.lfbTextFieldLabel.setObjectName("lfbTextFieldLabel")
        self.gridLayout.addWidget(self.lfbTextFieldLabel, 1, 1, 1, 1)
        self.lfbTextFieldHelp = QtWidgets.QLabel(Form)
        self.lfbTextFieldHelp.setWordWrap(True)
        self.lfbTextFieldHelp.setObjectName("lfbTextFieldHelp")
        self.gridLayout.addWidget(self.lfbTextFieldHelp, 4, 1, 1, 1)
        self.lfbTextFieldDescriptionBtn = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lfbTextFieldDescriptionBtn.setFont(font)
        self.lfbTextFieldDescriptionBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbTextFieldDescriptionBtn.setStyleSheet("QToolButton{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin-right: 10px;\n"
"}")
        self.lfbTextFieldDescriptionBtn.setObjectName("lfbTextFieldDescriptionBtn")
        self.gridLayout.addWidget(self.lfbTextFieldDescriptionBtn, 2, 0, 1, 1)
        self.lfbComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbComboBox.sizePolicy().hasHeightForWidth())
        self.lfbComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lfbComboBox.setFont(font)
        self.lfbComboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.lfbComboBox.setCurrentText("")
        self.lfbComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.lfbComboBox.setObjectName("lfbComboBox")
        self.gridLayout.addWidget(self.lfbComboBox, 2, 1, 1, 1)
        self.lfbReplaceWidget = QtWidgets.QGridLayout()
        self.lfbReplaceWidget.setObjectName("lfbReplaceWidget")
        self.gridLayout.addLayout(self.lfbReplaceWidget, 3, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbTextFieldError.setText(_translate("Form", "ErrorLabel"))
        self.lfbTextFieldSuccess.setText(_translate("Form", "SuccessLabel"))
        self.lfbTextFieldLabel.setText(_translate("Form", "TextLabel"))
        self.lfbTextFieldHelp.setText(_translate("Form", "Text content in QLabel can wrap lines along word boundaries with the wordWrap property. By default, word wrap is disabled. To enable it use setWordWrap():\n"
"\n"
""))
        self.lfbTextFieldDescriptionBtn.setText(_translate("Form", "i"))
