# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/form/textarea.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 393)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 10, 0, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.lfbTextFieldUnit = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.lfbTextFieldUnit.setFont(font)
        self.lfbTextFieldUnit.setText("")
        self.lfbTextFieldUnit.setObjectName("lfbTextFieldUnit")
        self.gridLayout.addWidget(self.lfbTextFieldUnit, 1, 3, 1, 1)
        self.lfbTextFieldLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lfbTextFieldLabel.setFont(font)
        self.lfbTextFieldLabel.setObjectName("lfbTextFieldLabel")
        self.gridLayout.addWidget(self.lfbTextFieldLabel, 0, 2, 1, 1)
        self.lfbTextFieldSuccess = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lfbTextFieldSuccess.setFont(font)
        self.lfbTextFieldSuccess.setStyleSheet("color: green;")
        self.lfbTextFieldSuccess.setWordWrap(True)
        self.lfbTextFieldSuccess.setObjectName("lfbTextFieldSuccess")
        self.gridLayout.addWidget(self.lfbTextFieldSuccess, 5, 2, 1, 1)
        self.lfbTextFieldHelp = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbTextFieldHelp.sizePolicy().hasHeightForWidth())
        self.lfbTextFieldHelp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lfbTextFieldHelp.setFont(font)
        self.lfbTextFieldHelp.setWordWrap(True)
        self.lfbTextFieldHelp.setObjectName("lfbTextFieldHelp")
        self.gridLayout.addWidget(self.lfbTextFieldHelp, 3, 2, 1, 1)
        self.lfbTextFieldError = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lfbTextFieldError.setFont(font)
        self.lfbTextFieldError.setStyleSheet("color: red;")
        self.lfbTextFieldError.setWordWrap(True)
        self.lfbTextFieldError.setObjectName("lfbTextFieldError")
        self.gridLayout.addWidget(self.lfbTextFieldError, 4, 2, 1, 1)
        self.lfbTextFieldDescriptionBtn = QtWidgets.QToolButton(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lfbTextFieldDescriptionBtn.setFont(font)
        self.lfbTextFieldDescriptionBtn.setStyleSheet("QToolButton{\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin-right: 10px;\n"
"}")
        self.lfbTextFieldDescriptionBtn.setAutoRaise(False)
        self.lfbTextFieldDescriptionBtn.setObjectName("lfbTextFieldDescriptionBtn")
        self.gridLayout.addWidget(self.lfbTextFieldDescriptionBtn, 1, 0, 1, 1)
        self.lfbTextField = QtWidgets.QPlainTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lfbTextField.setFont(font)
        self.lfbTextField.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}")
        self.lfbTextField.setObjectName("lfbTextField")
        self.gridLayout.addWidget(self.lfbTextField, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbTextFieldLabel.setText(_translate("Form", "TextLabel"))
        self.lfbTextFieldSuccess.setText(_translate("Form", "SuccessLabel"))
        self.lfbTextFieldHelp.setText(_translate("Form", "Text content in QLabel can wrap lines along word boundaries with the wordWrap property. By default, word wrap is disabled. To enable it use setWordWrap():\n"
"\n"
""))
        self.lfbTextFieldError.setText(_translate("Form", "ErrorLabel"))
        self.lfbTextFieldDescriptionBtn.setText(_translate("Form", "i"))
