# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LfbRegenerationWildlifeImpactDialog
                                 A QGIS plugin
 Lfb Regeneration and Wildlife Impact Monitoring
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-08
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Grünecho
        email                : support@grunecho.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

#import json

from qgis.core import QgsMessageLog, QgsProject, QgsVectorLayer, QgsJsonUtils, QgsField, QgsFields, QgsVectorFileWriter, QgsCoordinateTransformContext
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtWidgets import QDialog

from PyQt5.uic import loadUi
from PyQt5 import QtCore

from ..textfield import TextField
from ..dropdown import DropDown

UI_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'tab_default2.ui'))


class Tab2(QtWidgets.QWidget, UI_CLASS):
    inputChanged = QtCore.pyqtSignal(object)

    def __init__(self, interface, json, schema):
        """Constructor."""

        QDialog.__init__(self, interface.mainWindow())

        self.setupUi(self)

        self.json = json

        self.show()

        self.access = DropDown(interface, self.json, schema, 'accessibility')
        self.lfbTabLayout.addWidget(self.access)
        self.access.inputChanged.connect(self.emitText)


        self.latitude = TextField(interface, self.json, schema, 'latitude')
        self.lfbTabLayout.addWidget(self.latitude)
        self.latitude.inputChanged.connect(self.emitText)

        self.longitude = TextField(interface, self.json, schema, 'longitude')
        self.lfbTabLayout.addWidget(self.longitude)
        self.longitude.inputChanged.connect(self.emitText)

    def setJson(self, newJson):
        self.json = newJson
        self.access.setJson(self.json)
        self.latitude.setJson(self.json)
        self.longitude.setJson(self.json)

    def emitText(self):
        self.inputChanged.emit(self.json)