# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LfbRegenerationWildlifeImpactDialog
                                 A QGIS plugin
 Lfb Regeneration and Wildlife Impact Monitoring
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-08
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Grünecho
        email                : support@grunecho.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import QgsFeature, QgsMessageLog, QgsProject, QgsVectorLayer, QgsMapLayer
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtWidgets import QDialog, QWidget

from PyQt5.uic import loadUi

import json
import copy

from .form.textfield import TextField

from .form.views.tabs import Tabs

from .draft.draft_selection import DraftSelection
from .setup.folder_selection import FolderSelection

from .form.saveBar import SaveBar

from jsonschema import Draft7Validator

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'lfb_regeneration_wildlife_impact_dialog_base.ui'))


class LfbRegenerationWildlifeImpactDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, interface, state):
        """Constructor.

        :type state: CurrentState
        """

        # super(LfbRegenerationWildlifeImpactDialog, self).__init__(parent)
        QDialog.__init__(self, interface.mainWindow())

        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        dirname = os.path.dirname(__file__)

        # QGIS interface
        self.iface = interface

        self.tabsArray = []

        filename = os.path.realpath(os.path.join(dirname, '..', 'schema', 'default.json'))

        with open(filename) as f:
            self.defaultJson = json.load(f)

        self.json = copy.deepcopy(self.defaultJson)

        self.state = state

        # Connect up the buttons.
        self.lfbHomeBtn.clicked.connect(self.openHome)
        self.lfbQuestionBtn.clicked.connect(self.openQuestionDialog)

        self.lfbDevBtn.clicked.connect(self.openState)
        
        self.addFolderSelection()
        self.addDraft()

        
        filename = os.path.realpath(os.path.join(dirname, '..', 'schema', 'vwm.json'))

        with open(filename) as f:
            self.schema = json.load(f)
        

        self.lfbNewEntry.clicked.connect(self.newEntry)

        tabNr = 1
        for attr, value in self.schema['properties'].items():
            tab = Tabs(self.iface, self.json[attr], self.schema['properties'][attr])
            tab.inputChanged.connect(self.inputChanged)
            #self.lfbTabWidget.addWidget(tab)
            #newTab = QWidget(myTabWidget)
            
            self.tabsArray.append(
                {
                    'tabNr': tabNr,
                    'setJson': tab.setJson,
                    'attr': attr
                }
            )
            self.lfbTabWidget.addTab(tab, value['title'])
            tabNr += 1

        self.saveBar = SaveBar(self.iface, self.json, self.schema)
        self.verticalLayout_4.addWidget(self.saveBar)

        self.resetForm(False)
        self.setPosition(1)

    def resetForm(self, setFields = True):

        for tab in self.tabsArray:
            tab['setJson'](self.json[tab['attr']], setFields)
        

    def newEntry(self):
        self.json = copy.deepcopy(self.defaultJson)
        self.changeState()
        self.setPosition(2)

    def inputChanged(self, save):
        self.changeState()

        #if self.saveBar.validate(self.json) == True:
        if self.validateTabs(True):
            self.draft.saveFeature(self.json)
        # if self.json['coordinates']['latitude'] != None and self.json['coordinates']['longitude'] != None and self.json['aufnahmetrupp'] != None and self.json['GNSSDevice'] != None:
            

    def openHome(self):
        self.json = copy.deepcopy(self.defaultJson)
        self.changeState()
        self.setPosition(1)

    def setPosition(self, position):

        self.userPosition = position

        if self.userPosition == 2:
            self.lfbNewEntry.hide()
            self.lfbTabWidget.show()
            self.saveBar.show()
            self.draft.hide()
            self.folderSelection.hide()
            self.lfbHomeBtn.setEnabled(True)
        elif self.userPosition == 3:
            self.lfbNewEntry.hide()
            self.lfbTabWidget.show()
            self.saveBar.show()
            self.draft.hide()
            self.folderSelection.hide()
            self.lfbHomeBtn.setEnabled(True)
        else: 
            self.lfbNewEntry.show()
            self.lfbTabWidget.hide()
            self.saveBar.hide()
            self.draft.show()
            self.folderSelection.show()
            self.lfbHomeBtn.setEnabled(False)

    def addFolderSelection(self):
        self.folderSelection = FolderSelection(self.iface)
        self.folderSelection.folderSelected.connect(self.folderSelected)
        self.verticalLayout_4.addWidget(self.folderSelection)
        

    def folderSelected(self, folderPath):
        self.draftPath = folderPath
        self.draft.setDraftPath(folderPath)

    def addDraft(self):
        self.draft = DraftSelection(self.iface)
        self.draft.draftSelected.connect(self.draftSelected)
        self.verticalLayout_4.addWidget(self.draft)

    def draftSelected(self, id):
        self.json = id
        self.resetForm(True)
        self.changeState()
        self.setPosition(2)

    def changeState(self):
        self.state.change_state(self.json)
        self.saveBar.validate(self.state.state)
        self.resetForm(False)
        self.validateTabs()

    def openState(self):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setText(json.dumps(self.state.state, indent=2))
        msgBox.exec()

    def openQuestionDialog(self):
        msg = self.tr('Infotext')

        QtWidgets.QMessageBox.information(
            self, "LFB Info", msg, QtWidgets.QMessageBox.Ok)
        
    def validateTabs(self, minimumToDraft = False):

        
        v = Draft7Validator(self.schema['properties']['general'])
        gErrors = sorted(v.iter_errors(self.state.state['general']), key=lambda e: e.path)

        if len(gErrors) == 0:
            self.lfbTabWidget.setTabEnabled(1, True)
        else:
            self.lfbTabWidget.setTabEnabled(1, False)


        v = Draft7Validator(self.schema['properties']['coordinates'])
        cErrors = sorted(v.iter_errors(self.state.state['coordinates']), key=lambda e: e.path)

        if len(cErrors) == 0:
            self.lfbTabWidget.setTabEnabled(2, True)
        else:
            self.lfbTabWidget.setTabEnabled(2, False)

        if minimumToDraft == True:
            return len(gErrors) == 0 and len(cErrors) == 0
        

