# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/lfb_regeneration_wildlife_impact_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LfbRegenerationWildlifeImpactDialogBase(object):
    def setupUi(self, LfbRegenerationWildlifeImpactDialogBase):
        LfbRegenerationWildlifeImpactDialogBase.setObjectName("LfbRegenerationWildlifeImpactDialogBase")
        LfbRegenerationWildlifeImpactDialogBase.resize(940, 695)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(LfbRegenerationWildlifeImpactDialogBase.sizePolicy().hasHeightForWidth())
        LfbRegenerationWildlifeImpactDialogBase.setSizePolicy(sizePolicy)
        LfbRegenerationWildlifeImpactDialogBase.setMinimumSize(QtCore.QSize(400, 100))
        self.gridLayout = QtWidgets.QGridLayout(LfbRegenerationWildlifeImpactDialogBase)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lfbMain = QtWidgets.QVBoxLayout()
        self.lfbMain.setObjectName("lfbMain")
        self.gridLayout.addLayout(self.lfbMain, 5, 0, 1, 1)
        self.lfbMenuBar_2 = QtWidgets.QWidget(LfbRegenerationWildlifeImpactDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbMenuBar_2.sizePolicy().hasHeightForWidth())
        self.lfbMenuBar_2.setSizePolicy(sizePolicy)
        self.lfbMenuBar_2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.lfbMenuBar_2.setObjectName("lfbMenuBar_2")
        self.lfbMenuBar = QtWidgets.QHBoxLayout(self.lfbMenuBar_2)
        self.lfbMenuBar.setContentsMargins(10, 10, 10, 10)
        self.lfbMenuBar.setObjectName("lfbMenuBar")
        self.lfbHomeBtn = QtWidgets.QToolButton(self.lfbMenuBar_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lfbHomeBtn.setFont(font)
        self.lfbHomeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbHomeBtn.setStyleSheet("color: #ffffff;")
        self.lfbHomeBtn.setObjectName("lfbHomeBtn")
        self.lfbMenuBar.addWidget(self.lfbHomeBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lfbMenuBar.addItem(spacerItem)
        self.lfbDevBtn = QtWidgets.QPushButton(self.lfbMenuBar_2)
        self.lfbDevBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbDevBtn.setStyleSheet("color: #fff;\n"
"background-color: #333;")
        self.lfbDevBtn.setObjectName("lfbDevBtn")
        self.lfbMenuBar.addWidget(self.lfbDevBtn)
        self.gridLayout.addWidget(self.lfbMenuBar_2, 0, 0, 1, 1)
        self.lfbNewEntry = QtWidgets.QPushButton(LfbRegenerationWildlifeImpactDialogBase)
        self.lfbNewEntry.setObjectName("lfbNewEntry")
        self.gridLayout.addWidget(self.lfbNewEntry, 1, 0, 1, 1)
        self.lfbTabWidget = QtWidgets.QTabWidget(LfbRegenerationWildlifeImpactDialogBase)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lfbTabWidget.setFont(font)
        self.lfbTabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lfbTabWidget.setStyleSheet("margin:0;padding:0;")
        self.lfbTabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.lfbTabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.lfbTabWidget.setDocumentMode(True)
        self.lfbTabWidget.setMovable(False)
        self.lfbTabWidget.setObjectName("lfbTabWidget")
        self.gridLayout.addWidget(self.lfbTabWidget, 4, 0, 1, 1)

        self.retranslateUi(LfbRegenerationWildlifeImpactDialogBase)
        self.lfbTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(LfbRegenerationWildlifeImpactDialogBase)

    def retranslateUi(self, LfbRegenerationWildlifeImpactDialogBase):
        _translate = QtCore.QCoreApplication.translate
        LfbRegenerationWildlifeImpactDialogBase.setWindowTitle(_translate("LfbRegenerationWildlifeImpactDialogBase", "Lfb Regeneration and Wildlife Impact Monitoring"))
        self.lfbHomeBtn.setText(_translate("LfbRegenerationWildlifeImpactDialogBase", "<"))
        self.lfbDevBtn.setText(_translate("LfbRegenerationWildlifeImpactDialogBase", "DEV"))
        self.lfbNewEntry.setText(_translate("LfbRegenerationWildlifeImpactDialogBase", "Neuer Eintrag"))
