# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LfbRegenerationWildlifeImpactDialog
                                 A QGIS plugin
 Lfb Regeneration and Wildlife Impact Monitoring
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-08
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Grünecho
        email                : support@grunecho.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import uuid
import json

from qgis.core import QgsMessageLog, QgsProject, QgsWkbTypes, QgsVectorFileWriter, QgsFeature, QgsGeometry, QgsPointXY
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QDialog
from qgis.PyQt.QtCore import QDateTime, QJsonDocument
from PyQt5.QtNetwork import  QNetworkAccessManager, QNetworkRequest, QNetworkReply
from PyQt5.QtCore import QCoreApplication, QUrl


#from PyQt5.uic import loadUi
from PyQt5 import QtCore, QtGui

#from ...utils.helper import Utils


UI_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'synchronization.ui'))

LOGIN_ENDPOINT = "https://db01.simplex4data.de/projekte/lfb/postgrest/rpc/login"
EXPORT_HOST = "http://localhost:3000/rpc/export_geojson"

class Synchronization(QtWidgets.QWidget, UI_CLASS):

    geojson_received = QtCore.pyqtSignal(object)

    def __init__(self, interface):
        """Constructor."""

        QDialog.__init__(self, interface.mainWindow())
        self.setupUi(self)



    def handleSyncResponse(self, reply):
        """
        Handle the response from the server.
        """

        response = json.loads(reply.readAll().data().decode())

        if reply.error():
            QgsMessageLog.logMessage(f'Error: {reply.errorString()}')
            return
        else:
            QgsMessageLog.logMessage(f'Response: {response}')
            self.geojson_received.emit(response)

    def add_geojson_from_host(self, host = None, token = None):
        """
        Get the geojson data from the host.
        """
        
        try:

            json = {
                "los_ids":[68]
            }
            document = QJsonDocument(json)

            QgsMessageLog.logMessage(f'Making a request to {EXPORT_HOST}')
            request = QNetworkRequest(QUrl(EXPORT_HOST))
            request.setHeader(QNetworkRequest.ContentTypeHeader, "application/json")


            self.nam = QNetworkAccessManager()
            self.nam.finished.connect(self.handleSyncResponse)
            self.nam.post(request, document.toJson())

        except Exception as e:
            QgsMessageLog.logMessage(e)
            QgsMessageLog.logMessage("An request error occurred")
    