# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/setup/errors.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lfbErrorsWrapper(object):
    def setupUi(self, lfbErrorsWrapper):
        lfbErrorsWrapper.setObjectName("lfbErrorsWrapper")
        lfbErrorsWrapper.resize(825, 441)
        lfbErrorsWrapper.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(lfbErrorsWrapper)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.lfbErrorsWidget = QtWidgets.QWidget(lfbErrorsWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbErrorsWidget.sizePolicy().hasHeightForWidth())
        self.lfbErrorsWidget.setSizePolicy(sizePolicy)
        self.lfbErrorsWidget.setStyleSheet("QWidget#lfbErrorsWidget{\n"
"    background-color: rgba(100,0,0);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"QWidget{\n"
"    background-color: rgba(100,0,0);\n"
"    color: white;\n"
"}")
        self.lfbErrorsWidget.setObjectName("lfbErrorsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.lfbErrorsWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lfbErrorsOfCount = QtWidgets.QLabel(self.lfbErrorsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbErrorsOfCount.sizePolicy().hasHeightForWidth())
        self.lfbErrorsOfCount.setSizePolicy(sizePolicy)
        self.lfbErrorsOfCount.setObjectName("lfbErrorsOfCount")
        self.horizontalLayout.addWidget(self.lfbErrorsOfCount)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lfbErrorLocation = QtWidgets.QLabel(self.lfbErrorsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbErrorLocation.sizePolicy().hasHeightForWidth())
        self.lfbErrorLocation.setSizePolicy(sizePolicy)
        self.lfbErrorLocation.setObjectName("lfbErrorLocation")
        self.verticalLayout.addWidget(self.lfbErrorLocation)
        self.lfbErrorDescription = QtWidgets.QLabel(self.lfbErrorsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbErrorDescription.sizePolicy().hasHeightForWidth())
        self.lfbErrorDescription.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbErrorDescription.setFont(font)
        self.lfbErrorDescription.setStyleSheet("padding:0;")
        self.lfbErrorDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lfbErrorDescription.setObjectName("lfbErrorDescription")
        self.verticalLayout.addWidget(self.lfbErrorDescription)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.lfbErrorsWidget, 0, 0, 1, 1)

        self.retranslateUi(lfbErrorsWrapper)
        QtCore.QMetaObject.connectSlotsByName(lfbErrorsWrapper)

    def retranslateUi(self, lfbErrorsWrapper):
        _translate = QtCore.QCoreApplication.translate
        lfbErrorsWrapper.setWindowTitle(_translate("lfbErrorsWrapper", "Form"))
        self.lfbErrorsOfCount.setText(_translate("lfbErrorsWrapper", "1/3"))
        self.lfbErrorLocation.setText(_translate("lfbErrorsWrapper", "ErrorLocation"))
        self.lfbErrorDescription.setText(_translate("lfbErrorsWrapper", "ErrorDescription"))
