# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/lfb-regeneration_wildlife_impact_monitoring/lfb_regeneration_wildlife_impact/gui/setup/folder_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(848, 388)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(-1, 50, -1, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.lfbFolderSelectionError = QtWidgets.QLabel(Form)
        self.lfbFolderSelectionError.setObjectName("lfbFolderSelectionError")
        self.gridLayout.addWidget(self.lfbFolderSelectionError, 3, 2, 1, 3)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 4)
        self.lfbTempAlert = QtWidgets.QLabel(Form)
        self.lfbTempAlert.setStyleSheet("color: orange;")
        self.lfbTempAlert.setAlignment(QtCore.Qt.AlignCenter)
        self.lfbTempAlert.setObjectName("lfbTempAlert")
        self.gridLayout.addWidget(self.lfbTempAlert, 1, 2, 1, 2)
        self.lfbFolderSelection = gui.QgsFileWidget(Form)
        self.lfbFolderSelection.setFullUrl(False)
        self.lfbFolderSelection.setStorageMode(gui.QgsFileWidget.GetDirectory)
        self.lfbFolderSelection.setOptions(QtWidgets.QFileDialog.ReadOnly|QtWidgets.QFileDialog.ShowDirsOnly)
        self.lfbFolderSelection.setObjectName("lfbFolderSelection")
        self.gridLayout.addWidget(self.lfbFolderSelection, 2, 2, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbFolderSelectionError.setText(_translate("Form", "Select a folder you want to save data in."))
        self.label.setText(_translate("Form", "Speicherort"))
        self.lfbTempAlert.setText(_translate("Form", "!! Deine Daten werden aktuell nur temporär gespeichert !!"))
from qgis import gui
