# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LfbRegenerationWildlifeImpactDialog
                                 A QGIS plugin
 Lfb Regeneration and Wildlife Impact Monitoring
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-08
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Grünecho
        email                : support@grunecho.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import json

from qgis.core import QgsMessageLog, QgsProject, QgsVectorLayer, QgsJsonUtils, QgsField, QgsFields, QgsFeature, QgsGeometry, QgsPointXY, QgsMapLayer
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtWidgets import QDialog

from PyQt5.uic import loadUi
from PyQt5 import QtCore
from qgis.PyQt.QtCore import QVariant

import subprocess


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
UI_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'folder_selection.ui'))


class FolderSelection(QtWidgets.QWidget, UI_CLASS):
    # https://forum.qt.io/topic/133959/example-of-calling-a-function-to-parent/6
    folderSelected = QtCore.pyqtSignal(str)

    def __init__(self, interface):
        """Constructor."""

        QDialog.__init__(self, interface.mainWindow())

        self.setupUi(self)

        # QGIS interface
        self.iface = interface


        self.lfbFolderSelection.fileChanged.connect(self.selectFolder)

        self.show()

    def setFolder(self, path):
        self.path = path
        self.lfbFolderSelection.setFilePath(self.path)
        self.lfbTempAlert.hide()
        QgsProject.instance().write()

    def selectFolder(self):
        path = self.lfbFolderSelection.filePath()
        if os.path.exists(path):
            self.lfbFolderSelectionError.setText("Thanks!")
            self.lfbFolderSelectionError.setStyleSheet("color: green")
            self.folderSelected.emit(path)
        else:
            self.lfbFolderSelectionError.setText("Folder does not exist. Select another one.")
            self.lfbFolderSelectionError.setStyleSheet("color: red")
            

